[project]
name = "notebook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "azure-ai-projects>=2.0.0b2",
    "azure-identity>=1.25.1",
    "openai>=2.8.1",
    "python-dotenv>=1.2.1",
]
