[project]
name = "mage-guild-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.123.0",
    "fastapi-cli>=0.0.16",
]
