name: Create Azure Foundry resources

on:
  workflow_dispatch:
    inputs:
      use-azure-managed-ressources:
        type: boolean
        description: Use Azure Managed resources for Foundry
        default: true
jobs:
  create-azure-resources:
    env:
      REGION: "westus" # You can change this to reflect the region where you deploy your Accelerator
      AZURE_CORE_OUTPUT: "none" # Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Temp fix
      - name: bicep tmp fix
        run: az config set bicep.use_binary_from_path=false

      - name: deploy
        id: createResources
        run: |
          az deployment sub create \
            --location ${{ env.REGION }} \
            --name ${{ github.run_id }} \
            --template-file ./infra/foundry.bicep \
            --parameters ./infra/foundry.bicepparam useAzureManagedResources=${{ inputs.use-azure-managed-ressources }} \
            --query 'properties.outputs' \
            --output json > outputs.json

          echo "resourceGroupName=$(jq -r '.resourceGroupName.value' outputs.json)" >> $GITHUB_OUTPUT
          echo "azureFoundryResourceName=$(jq -r '.azureFoundryResourceName.value' outputs.json)" >> $GITHUB_OUTPUT
          echo "azureFoundryResourceId=$(jq -r '.azureFoundryResourceId.value' outputs.json)" >> $GITHUB_OUTPUT
          echo "azureFoundryProjectResourceName=$(jq -r '.azureFoundryProjectResourceName.value' outputs.json)" >> $GITHUB_OUTPUT
          echo "azureFoundryProjectResourceId=$(jq -r '.azureFoundryProjectResourceId.value' outputs.json)" >> $GITHUB_OUTPUT
          echo "aiSearchConnection=$(jq -r '.aiSearchConnection.value' outputs.json)" >> $GITHUB_OUTPUT
          echo "azureStorageConnection=$(jq -r '.azureStorageConnection.value' outputs.json)" >> $GITHUB_OUTPUT
          echo "cosmosDBConnection=$(jq -r '.cosmosDBConnection.value' outputs.json)" >> $GITHUB_OUTPUT
          echo "projectWorkspaceId=$(jq -r '.projectWorkspaceId.value' outputs.json)" >> $GITHUB_OUTPUT
          echo "aiSearchResourceName=$(jq -r '.aiSearchResourceName.value' outputs.json)" >> $GITHUB_OUTPUT
          echo "azureStorageResourceName=$(jq -r '.azureStorageResourceName.value' outputs.json)" >> $GITHUB_OUTPUT
          echo "cosmosDBResourceName=$(jq -r '.cosmosDBResourceName.value' outputs.json)" >> $GITHUB_OUTPUT
          echo "foundryProjectProjectPrincipalId=$(jq -r '.foundryProjectProjectPrincipalId.value' outputs.json)" >> $GITHUB_OUTPUT

      - name: Debug outputs
        run: |
          echo "Resource Group Name: ${{ steps.createResources.outputs.resourceGroupName }}"
          echo "Foundry Name: ${{ steps.createResources.outputs.azureFoundryResourceName }}"
          echo "All outputs: ${{ toJSON(steps.createResources.outputs) }}"

      - name: Set secrets using gh CLI
        env:
          GH_TOKEN: ${{ secrets.PA_TOKEN }}
        run: |
          gh secret set RESOURCE_GROUP_NAME --body "${{ steps.createResources.outputs.resourceGroupName }}"
          gh secret set AZURE_FOUNDRY_RESOURCE_NAME --body "${{ steps.createResources.outputs.azureFoundryResourceName }}"
          gh secret set AZURE_FOUNDRY_RESOURCE_ID --body "${{ steps.createResources.outputs.azureFoundryResourceId }}"
          gh secret set AZURE_FOUNDRY_PROJECT_RESOURCE_NAME --body "${{ steps.createResources.outputs.azureFoundryProjectResourceName }}"
          gh secret set AZURE_FOUNDRY_PROJECT_RESOURCE_ID --body "${{ steps.createResources.outputs.azureFoundryProjectResourceId }}"
          gh secret set AI_SEARCH_CONNECTION --body "${{ steps.createResources.outputs.aiSearchConnection }}"
          gh secret set AZURE_STORAGE_CONNECTION --body "${{ steps.createResources.outputs.azureStorageConnection }}"
          gh secret set COSMOSDB_CONNECTION --body "${{ steps.createResources.outputs.cosmosDBConnection }}"
          gh secret set PROJECT_WORKSPACE_ID --body "${{ steps.createResources.outputs.projectWorkspaceId }}"
          gh secret set AI_SEARCH_RESOURCE_NAME --body "${{ steps.createResources.outputs.aiSearchResourceName }}"
          gh secret set AZURE_STORAGE_RESOURCENAME --body "${{ steps.createResources.outputs.azureStorageResourceName }}"
          gh secret set COSMOSDB_RESOURCE_NAME --body "${{ steps.createResources.outputs.cosmosDBResourceName }}"
          gh secret set FOUNDRY_PROJECT_PROJECTPRINCIPALID --body "${{ steps.createResources.outputs.foundryProjectProjectPrincipalId }}"

      # - name: deploy
      #   id: createResources
      #   uses: azure/arm-deploy@v2
      #   with:
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
      #     scope: subscription
      #     region: ${{ env.REGION }}
      #     deploymentName: ${{ github.run_id }}
      #     template: ./infra/foundry.bicep
      #     parameters: ./infra/foundry.bicepparam useAzureManagedResources=${{ inputs.use-azure-managed-ressources }}

      # - name: Debug outputs
      #   run: |
      #     echo "Resource Group Name: ${{ steps.createResources.outputs.resourceGroupName }}"
      #     echo "Foundry Name: ${{ steps.createResources.outputs.azureFoundryResourceName }}"
      #     echo "All outputs: ${{ toJSON(steps.createResources.outputs) }}"

      # - name: Set secrets using gh CLI
      #   env:
      #     GH_TOKEN: ${{ secrets.PA_TOKEN }}
      #   run: |
      #     gh secret set RESOURCE_GROUP_NAME --body "${{ steps.createResources.outputs.resourceGroupName }}"
      #     gh secret set AZURE_FOUNDRY_RESOURCE_NAME --body "${{ steps.createResources.outputs.azureFoundryResourceName }}"
      #     gh secret set AZURE_FOUNDRY_RESOURCE_ID --body "${{ steps.createResources.outputs.azureFoundryResourceId }}"
      #     gh secret set AZURE_FOUNDRY_PROJECT_RESOURCE_NAME --body "${{ steps.createResources.outputs.azureFoundryProjectResourceName }}"
      #     gh secret set AZURE_FOUNDRY_PROJECT_RESOURCE_ID --body "${{ steps.createResources.outputs.azureFoundryProjectResourceId }}"
      #     gh secret set AI_SEARCH_CONNECTION --body "${{ steps.createResources.outputs.aiSearchConnection }}"
      #     gh secret set AZURE_STORAGE_CONNECTION --body "${{ steps.createResources.outputs.azureStorageConnection }}"
      #     gh secret set COSMOSDB_CONNECTION --body "${{ steps.createResources.outputs.cosmosDBConnection }}"
      #     gh secret set PROJECT_WORKSPACE_ID --body "${{ steps.createResources.outputs.projectWorkspaceId }}"
      #     gh secret set AI_SEARCH_RESOURCE_NAME --body "${{ steps.createResources.outputs.aiSearchResourceName }}"
      #     gh secret set AZURE_STORAGE_RESOURCENAME --body "${{ steps.createResources.outputs.azureStorageResourceName }}"
      #     gh secret set COSMOSDB_RESOURCE_NAME --body "${{ steps.createResources.outputs.cosmosDBResourceName }}"
      #     gh secret set FOUNDRY_PROJECT_PROJECTPRINCIPALID --body "${{ steps.createResources.outputs.foundryProjectProjectPrincipalId }}"

      # - uses: gliech/create-github-secret-action@v1
      #   with:
      #     name: RESOURCE_GROUP_NAME
      #     value: ${{ steps.createResources.outputs.resourceGroupName }}
      #     pa_token: ${{ secrets.PA_TOKEN }}

      # - uses: gliech/create-github-secret-action@v1
      #   with:
      #     name: AZURE_FOUNDRY_RESOURCE_NAME
      #     value: ${{ steps.createResources.outputs.azureFoundryResourceName }}
      #     pa_token: ${{ secrets.PA_TOKEN }}

      # - uses: gliech/create-github-secret-action@v1
      #   with:
      #     name: AZURE_FOUNDRY_RESOURCE_ID
      #     value: ${{ steps.createResources.outputs.azureFoundryResourceId }}
      #     pa_token: ${{ secrets.PA_TOKEN }}

      # - uses: gliech/create-github-secret-action@v1
      #   with:
      #     name: AZURE_FOUNDRY_PROJECT_RESOURCE_NAME
      #     value: ${{ steps.createResources.outputs.azureFoundryProjectResourceName }}
      #     pa_token: ${{ secrets.PA_TOKEN }}

      # - uses: gliech/create-github-secret-action@v1
      #   with:
      #     name: AZURE_FOUNDRY_PROJECT_RESOURCE_ID
      #     value: ${{ steps.createResources.outputs.azureFoundryProjectResourceId }}
      #     pa_token: ${{ secrets.PA_TOKEN }}

      # - uses: gliech/create-github-secret-action@v1
      #   with:
      #     name: AI_SEARCH_CONNECTION
      #     value: ${{ steps.createResources.outputs.aiSearchConnection }}
      #     pa_token: ${{ secrets.PA_TOKEN }}

      # - uses: gliech/create-github-secret-action@v1
      #   with:
      #     name: AZURE_STORAGE_CONNECTION
      #     value: ${{ steps.createResources.outputs.azureStorageConnection }}
      #     pa_token: ${{ secrets.PA_TOKEN }}

      # - uses: gliech/create-github-secret-action@v1
      #   with:
      #     name: COSMOSDB_CONNECTION
      #     value: ${{ steps.createResources.outputs.cosmosDBConnection }}
      #     pa_token: ${{ secrets.PA_TOKEN }}

      # - uses: gliech/create-github-secret-action@v1
      #   with:
      #     name: PROJECT_WORKSPACE_ID
      #     value: ${{ steps.createResources.outputs.projectWorkspaceId}}
      #     pa_token: ${{ secrets.PA_TOKEN }}

      # - uses: gliech/create-github-secret-action@v1
      #   with:
      #     name: AI_SEARCH_RESOURCE_NAME
      #     value: ${{ steps.createResources.outputs.aiSearchResourceName}}
      #     pa_token: ${{ secrets.PA_TOKEN }}

      # - uses: gliech/create-github-secret-action@v1
      #   with:
      #     name: AZURE_STORAGE_RESOURCENAME
      #     value: ${{ steps.createResources.outputs.azureStorageResourceName}}
      #     pa_token: ${{ secrets.PA_TOKEN }}

      # - uses: gliech/create-github-secret-action@v1
      #   with:
      #     name: COSMOSDB_RESOURCE_NAME
      #     value: ${{ steps.createResources.outputs.cosmosDBResourceName}}
      #     pa_token: ${{ secrets.PA_TOKEN }}

      # - uses: gliech/create-github-secret-action@v1
      #   with:
      #     name: FOUNDRY_PROJECT_PROJECTPRINCIPALID
      #     value: ${{ steps.createResources.outputs.foundryProjectProjectPrincipalId}}
      #     pa_token: ${{ secrets.PA_TOKEN }}
